import Head from "next/head";

import StaffCollapse from "../components/Collapses/StaffCollapse.js";

import Slider from "../components/Slider";
import ProductCarCollappse from "../components/Collapses/ProductCarCollappse.js";

const images = [
  "/images/tabriz/tabriz.jpg",
  "/images/tabriz/ShahGoli.jpeg",
  "/images/tabriz/bazar.jpeg",
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Slider images={images} /> */}

      <StaffCollapse />

      <ProductCarCollappse />
      
    </>
  );
}
